In [1]:
import cv2
import mediapipe as mp
import numpy as np

In [2]:
def RGB(event, x, y, flags, param):
    if event == cv2.EVENT_MOUSEMOVE :  
        colorsBGR = [x, y]
        print(colorsBGR)

In [5]:
area1 = [(1911, 248),(7, 248),(8, 9),(1911, 10)] 
cv2.namedWindow('RGB')
cv2.setMouseCallback('RGB', RGB)
cap = cv2.VideoCapture(0)
count = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break
    cv2.polylines(frame,[np.array(area1,np.int32)], True, (255,0,0), 3)    
    cv2.imshow("RGB", frame)
    if cv2.waitKey(1) & 0xFF == 27:
        break
cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[119, 755]
[212, 817]
[466, 988]


-1

In [ ]:
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
area1 = [(1911, 248),(7, 248),(8, 9),(1911, 10)] 

cap = cv2.VideoCapture(0)

with mp_hands.Hands(static_image_mode = False, max_num_hands = 2, min_detection_confidence = 0.4) as hands:
    while True:
        success, image = cap.read()
        if not success:
            break

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        results = hands.process(image_rgb)

        if results.multi_hand_landmarks: 
            arr = np.array(results.multi_hand_landmarks)
            no_hands = arr.shape[0]   
            for i in range(0, no_hands):
                hand_landmarks = results.multi_hand_landmarks[i] 
                
                landmarks = hand_landmarks.landmark 
                landmark_x = [landmark.x for landmark in landmarks] 
                landmark_y = [landmark.y for landmark in landmarks]
            
                x_min, x_max = min(landmark_x), max(landmark_x)
                y_min, y_max = min(landmark_y), max(landmark_y)

                index_xmin = landmark_x.index(x_min)
                index_xmax = landmark_x.index(x_max)
                index_ymin = landmark_y.index(y_min)
                index_ymax = landmark_y.index(y_max)

                x_ymax = landmark_x[index_ymax]
                x_ymin = landmark_x[index_ymin]
                y_xmax = landmark_y[index_xmax]
                y_xmin = landmark_y[index_xmin]

                image_height, image_width, _ = image.shape
                x_min1, y_min1 = int(x_min * image_width), int(y_min * image_height)
                x_max1, y_max1 = int(x_max * image_width), int(y_max * image_height)

                y_xmin = int(y_xmin * image_height)
                y_xmax = int(y_xmax * image_height)
                x_ymin = int(x_ymin * image_width)
                x_ymax = int(x_ymax * image_width)

                cv2.circle(image, (x_min1 , y_min1), 10, (255,0,255), -1)
                cv2.circle(image, (x_max1 , y_max1), 10, (255,0,255), -1)

                cv2.circle(image, (x_min1 , y_xmin), 10, (0, 0,255), -1)
                cv2.circle(image, (x_max1 , y_xmax), 10, (0, 0,255), -1)
                cv2.circle(image, (x_ymin , y_min1), 10, (0, 0,255), -1)
                cv2.circle(image, (x_ymax , y_max1), 10, (0, 0,255), -1)

                cv2.rectangle(image, (x_min1, y_min1), (x_max1, y_max1), (0, 255, 0), 2)

                pos = cv2.pointPolygonTest(np.array(area1,np.int32), ((x_min1 , y_min1)), False)
                if pos >= 0:
                    cv2.putText(image, "Hand Up" ,(466, 988),cv2.FONT_HERSHEY_COMPLEX,(1),(255,255,255),4)
                
        cv2.polylines(image,[np.array(area1,np.int32)], True, (255,0,0), 3)    
        cv2.imshow('Hand Detection', image)
        
        if cv2.waitKey(1) & 0xFF == 27:
            break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

In [4]:
results

mediapipe.python.solution_base.SolutionOutputs

In [ ]:
print(type(results.multi_hand_landmarks))
print(len(results.multi_hand_landmarks))

In [16]:
results.multi_hand_landmarks

[landmark {
   x: 0.79619145
   y: 0.6409359
   z: 3.6862247e-07
 }
 landmark {
   x: 0.7371646
   y: 0.6388884
   z: -0.026737038
 }
 landmark {
   x: 0.6834463
   y: 0.5956001
   z: -0.04071197
 }
 landmark {
   x: 0.64446205
   y: 0.54429674
   z: -0.052003156
 }
 landmark {
   x: 0.60829556
   y: 0.5150486
   z: -0.06310589
 }
 landmark {
   x: 0.70204157
   y: 0.43744004
   z: -0.02200137
 }
 landmark {
   x: 0.67075354
   y: 0.35222182
   z: -0.03780188
 }
 landmark {
   x: 0.653855
   y: 0.2984272
   z: -0.05145287
 }
 landmark {
   x: 0.6413108
   y: 0.24654417
   z: -0.06256832
 }
 landmark {
   x: 0.736779
   y: 0.40476975
   z: -0.023288777
 }
 landmark {
   x: 0.7189243
   y: 0.29701346
   z: -0.035871617
 }
 landmark {
   x: 0.7096362
   y: 0.22972682
   z: -0.048354466
 }
 landmark {
   x: 0.7014956
   y: 0.16834977
   z: -0.0586926
 }
 landmark {
   x: 0.77222455
   y: 0.3985326
   z: -0.028284252
 }
 landmark {
   x: 0.76024246
   y: 0.29945874
   z: -0.044049583
 }
 la

In [21]:
results.multi_hand_landmarks[0]

landmark {
  x: 0.79619145
  y: 0.6409359
  z: 3.6862247e-07
}
landmark {
  x: 0.7371646
  y: 0.6388884
  z: -0.026737038
}
landmark {
  x: 0.6834463
  y: 0.5956001
  z: -0.04071197
}
landmark {
  x: 0.64446205
  y: 0.54429674
  z: -0.052003156
}
landmark {
  x: 0.60829556
  y: 0.5150486
  z: -0.06310589
}
landmark {
  x: 0.70204157
  y: 0.43744004
  z: -0.02200137
}
landmark {
  x: 0.67075354
  y: 0.35222182
  z: -0.03780188
}
landmark {
  x: 0.653855
  y: 0.2984272
  z: -0.05145287
}
landmark {
  x: 0.6413108
  y: 0.24654417
  z: -0.06256832
}
landmark {
  x: 0.736779
  y: 0.40476975
  z: -0.023288777
}
landmark {
  x: 0.7189243
  y: 0.29701346
  z: -0.035871617
}
landmark {
  x: 0.7096362
  y: 0.22972682
  z: -0.048354466
}
landmark {
  x: 0.7014956
  y: 0.16834977
  z: -0.0586926
}
landmark {
  x: 0.77222455
  y: 0.3985326
  z: -0.028284252
}
landmark {
  x: 0.76024246
  y: 0.29945874
  z: -0.044049583
}
landmark {
  x: 0.75115275
  y: 0.23827007
  z: -0.054622434
}
landmark {
  x:

In [15]:
landmarks 

[x: 0.79619145
y: 0.6409359
z: 3.6862247e-07
, x: 0.7371646
y: 0.6388884
z: -0.026737038
, x: 0.6834463
y: 0.5956001
z: -0.04071197
, x: 0.64446205
y: 0.54429674
z: -0.052003156
, x: 0.60829556
y: 0.5150486
z: -0.06310589
, x: 0.70204157
y: 0.43744004
z: -0.02200137
, x: 0.67075354
y: 0.35222182
z: -0.03780188
, x: 0.653855
y: 0.2984272
z: -0.05145287
, x: 0.6413108
y: 0.24654417
z: -0.06256832
, x: 0.736779
y: 0.40476975
z: -0.023288777
, x: 0.7189243
y: 0.29701346
z: -0.035871617
, x: 0.7096362
y: 0.22972682
z: -0.048354466
, x: 0.7014956
y: 0.16834977
z: -0.0586926
, x: 0.77222455
y: 0.3985326
z: -0.028284252
, x: 0.76024246
y: 0.29945874
z: -0.044049583
, x: 0.75115275
y: 0.23827007
z: -0.054622434
, x: 0.7412517
y: 0.18045917
z: -0.06267918
, x: 0.8084892
y: 0.410723
z: -0.0356917
, x: 0.8075021
y: 0.33274725
z: -0.0509943
, x: 0.8069066
y: 0.2812223
z: -0.057040248
, x: 0.80463904
y: 0.22972427
z: -0.061379347
]

In [ ]:
import numpy as np
arr = np.array(results.multi_hand_landmarks)
arr.shape[0]

In [151]:
len(landmarks)
landmarks[0]

x: 0.35202825
y: 0.9314307
z: -1.5992345e-07

In [155]:
image

array([[[ 62, 143, 167],
        [ 60, 139, 163],
        [ 59, 135, 162],
        ...,
        [ 20,  16,  32],
        [ 25,  21,  40],
        [ 32,  28,  47]],

       [[ 63, 144, 168],
        [ 62, 140, 164],
        [ 58, 134, 160],
        ...,
        [ 23,  20,  34],
        [ 27,  23,  39],
        [ 25,  22,  38]],

       [[ 65, 144, 168],
        [ 65, 143, 170],
        [ 60, 135, 165],
        ...,
        [ 22,  17,  28],
        [ 20,  15,  29],
        [ 19,  14,  28]],

       ...,

       [[ 11,  21,  29],
        [  5,  17,  24],
        [  0,  12,  20],
        ...,
        [124, 153, 145],
        [124, 152, 147],
        [124, 152, 147]],

       [[ 13,  21,  27],
        [ 10,  21,  26],
        [  3,  16,  23],
        ...,
        [122, 149, 142],
        [122, 148, 144],
        [121, 147, 142]],

       [[ 11,  19,  25],
        [  9,  19,  25],
        [  6,  18,  26],
        ...,
        [122, 149, 142],
        [120, 146, 141],
        [119, 145, 140]]

In [83]:
image[0] 

array([[ 90, 194, 238],
       [ 91, 195, 239],
       [ 88, 191, 236],
       ...,
       [108, 120, 119],
       [115, 127, 124],
       [120, 132, 128]], dtype=uint8)

In [76]:
image[0][0] 

array([ 90, 194, 238], dtype=uint8)

In [79]:
image[1079][1919] 

array([145, 156, 127], dtype=uint8)

In [22]:
cap.release()